version: "3.8"

#  docker logs neo4j-container
#  docker exec -it neo4j-container bash
#  docker-compose up -d
#  docker-compose down

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    restart: unless-stopped
    ports:
      - "7474:7474"  # Neo4j Web Interface
      - "7687:7687"  # Bolt Protocol
    environment:
      NEO4J_AUTH: neo4j/synthpop_123
      NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"
      NEO4J_server_directories_import: "/var/lib/neo4j/import"
      NEO4J_dbms_memory_pagecache_size: 1G  # Optional tuning
      NEO4J_dbms_memory_heap_initial__size: 4G
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_memory_transaction_total__max: 4G
    volumes:
      - /Users/Smoxon/.data/synthetic_populations:/var/lib/neo4j/import
      - neo4j-data:/data  # Stores Neo4j database data
      - neo4j-logs:/logs  # Stores logs

volumes:
  neo4j-data:
  neo4j-logs:
